#pragma once
#include "enum_macros.h"

#define REG_ENUM_StatusCode() \
	REG_ENUM(StatusCode) \
		ENUM(StatusCode, Good) \
		ENUM(StatusCode, BadUnexpectedError) \
		ENUM(StatusCode, BadInternalError) \
		ENUM(StatusCode, BadOutOfMemory) \
		ENUM(StatusCode, BadResourceUnavailable) \
		ENUM(StatusCode, BadCommunicationError) \
		ENUM(StatusCode, BadEncodingError) \
		ENUM(StatusCode, BadDecodingError) \
		ENUM(StatusCode, BadEncodingLimitsExceeded) \
		ENUM(StatusCode, BadRequestTooLarge) \
		ENUM(StatusCode, BadResponseTooLarge) \
		ENUM(StatusCode, BadUnknownResponse) \
		ENUM(StatusCode, BadTimeout) \
		ENUM(StatusCode, BadServiceUnsupported) \
		ENUM(StatusCode, BadShutdown) \
		ENUM(StatusCode, BadServerNotConnected) \
		ENUM(StatusCode, BadServerHalted) \
		ENUM(StatusCode, BadNothingToDo) \
		ENUM(StatusCode, BadTooManyOperations) \
		ENUM(StatusCode, BadTooManyMonitoredItems) \
		ENUM(StatusCode, BadDataTypeIdUnknown) \
		ENUM(StatusCode, BadCertificateInvalid) \
		ENUM(StatusCode, BadSecurityChecksFailed) \
		ENUM(StatusCode, BadCertificateTimeInvalid) \
		ENUM(StatusCode, BadCertificateIssuerTimeInvalid) \
		ENUM(StatusCode, BadCertificateHostNameInvalid) \
		ENUM(StatusCode, BadCertificateUriInvalid) \
		ENUM(StatusCode, BadCertificateUseNotAllowed) \
		ENUM(StatusCode, BadCertificateIssuerUseNotAllowed) \
		ENUM(StatusCode, BadCertificateUntrusted) \
		ENUM(StatusCode, BadCertificateRevocationUnknown) \
		ENUM(StatusCode, BadCertificateIssuerRevocationUnknown) \
		ENUM(StatusCode, BadCertificateRevoked) \
		ENUM(StatusCode, BadCertificateIssuerRevoked) \
		ENUM(StatusCode, BadUserAccessDenied) \
		ENUM(StatusCode, BadIdentityTokenInvalid) \
		ENUM(StatusCode, BadIdentityTokenRejected) \
		ENUM(StatusCode, BadSecureChannelIdInvalid) \
		ENUM(StatusCode, BadInvalidTimestamp) \
		ENUM(StatusCode, BadNonceInvalid) \
		ENUM(StatusCode, BadSessionIdInvalid) \
		ENUM(StatusCode, BadSessionClosed) \
		ENUM(StatusCode, BadSessionNotActivated) \
		ENUM(StatusCode, BadSubscriptionIdInvalid) \
		ENUM(StatusCode, BadRequestHeaderInvalid) \
		ENUM(StatusCode, BadTimestampsToReturnInvalid) \
		ENUM(StatusCode, BadRequestCancelledByClient) \
		ENUM(StatusCode, GoodSubscriptionTransferred) \
		ENUM(StatusCode, GoodCompletesAsynchronously) \
		ENUM(StatusCode, GoodOverload) \
		ENUM(StatusCode, GoodClamped) \
		ENUM(StatusCode, BadNoCommunication) \
		ENUM(StatusCode, BadWaitingForInitialData) \
		ENUM(StatusCode, BadNodeIdInvalid) \
		ENUM(StatusCode, BadNodeIdUnknown) \
		ENUM(StatusCode, BadAttributeIdInvalid) \
		ENUM(StatusCode, BadIndexRangeInvalid) \
		ENUM(StatusCode, BadIndexRangeNoData) \
		ENUM(StatusCode, BadDataEncodingInvalid) \
		ENUM(StatusCode, BadDataEncodingUnsupported) \
		ENUM(StatusCode, BadNotReadable) \
		ENUM(StatusCode, BadNotWritable) \
		ENUM(StatusCode, BadOutOfRange) \
		ENUM(StatusCode, BadNotSupported) \
		ENUM(StatusCode, BadNotFound) \
		ENUM(StatusCode, BadObjectDeleted) \
		ENUM(StatusCode, BadNotImplemented) \
		ENUM(StatusCode, BadMonitoringModeInvalid) \
		ENUM(StatusCode, BadMonitoredItemIdInvalid) \
		ENUM(StatusCode, BadMonitoredItemFilterInvalid) \
		ENUM(StatusCode, BadMonitoredItemFilterUnsupported) \
		ENUM(StatusCode, BadFilterNotAllowed) \
		ENUM(StatusCode, BadStructureMissing) \
		ENUM(StatusCode, BadEventFilterInvalid) \
		ENUM(StatusCode, BadContentFilterInvalid) \
		ENUM(StatusCode, BadFilterOperatorInvalid) \
		ENUM(StatusCode, BadFilterOperatorUnsupported) \
		ENUM(StatusCode, BadFilterOperandCountMismatch) \
		ENUM(StatusCode, BadFilterOperandInvalid) \
		ENUM(StatusCode, BadFilterElementInvalid) \
		ENUM(StatusCode, BadFilterLiteralInvalid) \
		ENUM(StatusCode, BadContinuationPointInvalid) \
		ENUM(StatusCode, BadNoContinuationPoints) \
		ENUM(StatusCode, BadReferenceTypeIdInvalid) \
		ENUM(StatusCode, BadBrowseDirectionInvalid) \
		ENUM(StatusCode, BadNodeNotInView) \
		ENUM(StatusCode, BadServerUriInvalid) \
		ENUM(StatusCode, BadServerNameMissing) \
		ENUM(StatusCode, BadDiscoveryUrlMissing) \
		ENUM(StatusCode, BadSempahoreFileMissing) \
		ENUM(StatusCode, BadRequestTypeInvalid) \
		ENUM(StatusCode, BadSecurityModeRejected) \
		ENUM(StatusCode, BadSecurityPolicyRejected) \
		ENUM(StatusCode, BadTooManySessions) \
		ENUM(StatusCode, BadUserSignatureInvalid) \
		ENUM(StatusCode, BadApplicationSignatureInvalid) \
		ENUM(StatusCode, BadNoValidCertificates) \
		ENUM(StatusCode, BadIdentityChangeNotSupported) \
		ENUM(StatusCode, BadRequestCancelledByRequest) \
		ENUM(StatusCode, BadParentNodeIdInvalid) \
		ENUM(StatusCode, BadReferenceNotAllowed) \
		ENUM(StatusCode, BadNodeIdRejected) \
		ENUM(StatusCode, BadNodeIdExists) \
		ENUM(StatusCode, BadNodeClassInvalid) \
		ENUM(StatusCode, BadBrowseNameInvalid) \
		ENUM(StatusCode, BadBrowseNameDuplicated) \
		ENUM(StatusCode, BadNodeAttributesInvalid) \
		ENUM(StatusCode, BadTypeDefinitionInvalid) \
		ENUM(StatusCode, BadSourceNodeIdInvalid) \
		ENUM(StatusCode, BadTargetNodeIdInvalid) \
		ENUM(StatusCode, BadDuplicateReferenceNotAllowed) \
		ENUM(StatusCode, BadInvalidSelfReference) \
		ENUM(StatusCode, BadReferenceLocalOnly) \
		ENUM(StatusCode, BadNoDeleteRights) \
		ENUM(StatusCode, UncertainReferenceNotDeleted) \
		ENUM(StatusCode, BadServerIndexInvalid) \
		ENUM(StatusCode, BadViewIdUnknown) \
		ENUM(StatusCode, BadViewTimestampInvalid) \
		ENUM(StatusCode, BadViewParameterMismatch) \
		ENUM(StatusCode, BadViewVersionInvalid) \
		ENUM(StatusCode, UncertainNotAllNodesAvailable) \
		ENUM(StatusCode, GoodResultsMayBeIncomplete) \
		ENUM(StatusCode, BadNotTypeDefinition) \
		ENUM(StatusCode, UncertainReferenceOutOfServer) \
		ENUM(StatusCode, BadTooManyMatches) \
		ENUM(StatusCode, BadQueryTooComplex) \
		ENUM(StatusCode, BadNoMatch) \
		ENUM(StatusCode, BadMaxAgeInvalid) \
		ENUM(StatusCode, BadHistoryOperationInvalid) \
		ENUM(StatusCode, BadHistoryOperationUnsupported) \
		ENUM(StatusCode, BadInvalidTimestampArgument) \
		ENUM(StatusCode, BadWriteNotSupported) \
		ENUM(StatusCode, BadTypeMismatch) \
		ENUM(StatusCode, BadMethodInvalid) \
		ENUM(StatusCode, BadArgumentsMissing) \
		ENUM(StatusCode, BadTooManySubscriptions) \
		ENUM(StatusCode, BadTooManyPublishRequests) \
		ENUM(StatusCode, BadNoSubscription) \
		ENUM(StatusCode, BadSequenceNumberUnknown) \
		ENUM(StatusCode, BadMessageNotAvailable) \
		ENUM(StatusCode, BadInsufficientClientProfile) \
		ENUM(StatusCode, BadStateNotActive) \
		ENUM(StatusCode, BadTcpServerTooBusy) \
		ENUM(StatusCode, BadTcpMessageTypeInvalid) \
		ENUM(StatusCode, BadTcpSecureChannelUnknown) \
		ENUM(StatusCode, BadTcpMessageTooLarge) \
		ENUM(StatusCode, BadTcpNotEnoughResources) \
		ENUM(StatusCode, BadTcpInternalError) \
		ENUM(StatusCode, BadTcpEndpointUrlInvalid) \
		ENUM(StatusCode, BadRequestInterrupted) \
		ENUM(StatusCode, BadRequestTimeout) \
		ENUM(StatusCode, BadSecureChannelClosed) \
		ENUM(StatusCode, BadSecureChannelTokenUnknown) \
		ENUM(StatusCode, BadSequenceNumberInvalid) \
		ENUM(StatusCode, BadProtocolVersionUnsupported) \
		ENUM(StatusCode, BadConfigurationError) \
		ENUM(StatusCode, BadNotConnected) \
		ENUM(StatusCode, BadDeviceFailure) \
		ENUM(StatusCode, BadSensorFailure) \
		ENUM(StatusCode, BadOutOfService) \
		ENUM(StatusCode, BadDeadbandFilterInvalid) \
		ENUM(StatusCode, UncertainNoCommunicationLastUsableValue) \
		ENUM(StatusCode, UncertainLastUsableValue) \
		ENUM(StatusCode, UncertainSubstituteValue) \
		ENUM(StatusCode, UncertainInitialValue) \
		ENUM(StatusCode, UncertainSensorNotAccurate) \
		ENUM(StatusCode, UncertainEngineeringUnitsExceeded) \
		ENUM(StatusCode, UncertainSubNormal) \
		ENUM(StatusCode, GoodLocalOverride) \
		ENUM(StatusCode, BadRefreshInProgress) \
		ENUM(StatusCode, BadConditionAlreadyDisabled) \
		ENUM(StatusCode, BadConditionAlreadyEnabled) \
		ENUM(StatusCode, BadConditionDisabled) \
		ENUM(StatusCode, BadEventIdUnknown) \
		ENUM(StatusCode, BadEventNotAcknowledgeable) \
		ENUM(StatusCode, BadDialogNotActive) \
		ENUM(StatusCode, BadDialogResponseInvalid) \
		ENUM(StatusCode, BadConditionBranchAlreadyAcked) \
		ENUM(StatusCode, BadConditionBranchAlreadyConfirmed) \
		ENUM(StatusCode, BadConditionAlreadyShelved) \
		ENUM(StatusCode, BadConditionNotShelved) \
		ENUM(StatusCode, BadShelvingTimeOutOfRange) \
		ENUM(StatusCode, BadNoData) \
		ENUM(StatusCode, BadBoundNotFound) \
		ENUM(StatusCode, BadBoundNotSupported) \
		ENUM(StatusCode, BadDataLost) \
		ENUM(StatusCode, BadDataUnavailable) \
		ENUM(StatusCode, BadEntryExists) \
		ENUM(StatusCode, BadNoEntryExists) \
		ENUM(StatusCode, BadTimestampNotSupported) \
		ENUM(StatusCode, GoodEntryInserted) \
		ENUM(StatusCode, GoodEntryReplaced) \
		ENUM(StatusCode, UncertainDataSubNormal) \
		ENUM(StatusCode, GoodNoData) \
		ENUM(StatusCode, GoodMoreData) \
		ENUM(StatusCode, BadAggregateListMismatch) \
		ENUM(StatusCode, BadAggregateNotSupported) \
		ENUM(StatusCode, BadAggregateInvalidInputs) \
		ENUM(StatusCode, BadAggregateConfigurationRejected) \
		ENUM(StatusCode, GoodDataIgnored) \
		ENUM(StatusCode, GoodCommunicationEvent) \
		ENUM(StatusCode, GoodShutdownEvent) \
		ENUM(StatusCode, GoodCallAgain) \
		ENUM(StatusCode, GoodNonCriticalTimeout) \
		ENUM(StatusCode, BadInvalidArgument) \
		ENUM(StatusCode, BadConnectionRejected) \
		ENUM(StatusCode, BadDisconnect) \
		ENUM(StatusCode, BadConnectionClosed) \
		ENUM(StatusCode, BadInvalidState) \
		ENUM(StatusCode, BadEndOfStream) \
		ENUM(StatusCode, BadNoDataAvailable) \
		ENUM(StatusCode, BadWaitingForResponse) \
		ENUM(StatusCode, BadOperationAbandoned) \
		ENUM(StatusCode, BadExpectedStreamToBlock) \
		ENUM(StatusCode, BadWouldBlock) \
		ENUM(StatusCode, BadSyntaxError) \
	ENUM_END(StatusCode, BadMaxConnectionsReached)

